export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const ADD_PRODUCT_ITEM = 'ADD_PRODUCT_ITEM';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';